# mamba env create --file environment.yml
# mamba env update --file environment.yml
name: cool_solar_wind
channels:
  - conda-forge
dependencies:
  - jupyter
  - nodejs
  - bottleneck
  - xarray-einstats
  - plasmapy
  - bokeh<3 # pytplot compatibility
  # - bokeh
  - pyviz::hvplot
  - jupyter_bokeh
  - proplot
  - loguru
  - pip
  - pip:
    - pyspedas @ git+https://github.com/spedas/pyspedas